name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint || true
        
      - name: Build
        run: npm run build
        
      - name: Build development
        run: npm run build:dev
        
      - name: Run tests
        run: npm test
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: matrix.node-version == '18.x'
        with:
          name: dist-files
          path: dist/
          retention-days: 7 